
Vagrant.configure("2") do |config|
  config.vm.define :lesson_2_vm do |lesson_2_vm|
    lesson_2_vm.vm.box = "centos/7"
  end
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 14000
    libvirt.storage :file, :size => '1G'
    libvirt.storage :file, :size => '1G'
    libvirt.storage :file, :size => '1G'
    libvirt.storage :file, :size => '1G'
  end

  $script = <<-SCRIPT
    yum install mdadm -y &&
    mdadm --create --verbose /dev/md10 -l 10 -n 4 /dev/vdb /dev/vdc /dev/vdd /dev/vde &&
    mdadm --detail --scan >> /etc/mdadm.conf &&
    parted -s /dev/md10 mklabel gpt &&
    sudo parted -s /dev/md10 mkpart primary ext4 0% 20% &&
    sudo parted -s /dev/md10 mkpart primary ext4 20% 40% &&
    sudo parted -s /dev/md10 mkpart primary ext4 40% 60% && 
    sudo parted -s /dev/md10 mkpart primary ext4 60% 80% &&
    sudo parted -s /dev/md10 mkpart primary ext4 80% 100% &&
    for i in $(seq 1 5); do mkfs.ext4 /dev/md10p$i; done &&
    mkdir -p /raid/part{1,2,3,4,5} &&
    for i in $(seq 1 5); do mount /dev/md10p$i /raid/part$i; done &&
    for i in $(seq 1 5); do echo "/dev/md10p$i /raid/part$i ext4 defaults 0 0" >> /etc/fstab; done
  SCRIPT

  config.vm.provision "shell",
    inline: $script
end
